Rails.application.config.assets.precompile += %w( lemon_bonsai.css )
Rails.application.config.assets.precompile += %w( html5.js )
Rails.application.config.assets.precompile += %w( jquery-1.6.1.min.js )
Rails.application.config.assets.precompile += %w( jquery.masonry.min.js )
Rails.application.config.assets.precompile += %w( lemon_bonsai_js/producer.js )
